/*This file is autogenerated by build script. Do not modify.*/
/*jshint node:true*/
module.exports = {
	sortify: require('./arrayify.js').sortify,
	filterify: require('./arrayify.js').filterify,
	foreachify: require('./arrayify.js').foreachify,
	everyify: require('./arrayify.js').everyify,
	someify: require('./arrayify.js').someify,
	reduceify: require('./arrayify.js').reduceify,
	callbackify: require('./callbackify.js'),
	chainify: require('./chainify.js'),
	factorify: require('./factorify.js')
};
